apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: {{{name}}}
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    {{#each ingresses as |url|}}
       - {{url}}
    {{/each}}
{{#if azure}}
  azure:
    application:
      enabled: true
{{/if}}
  liveness:
    path: /tiltak-refusjon/internal/isAlive
    initialDelay: 5
  readiness:
    path: /tiltak-refusjon/internal/isReady
    initialDelay: 5
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: LOGIN_URL
      value: {{{login-url}}}
    - name: APIGW_URL
      value: "http://tiltak-refusjon-api"
    - name: DECORATOR_EXTERNAL_URL
      value: "{{{decorator-external-url}}}"
    - name: DECORATOR_INTERNAL_SCRIPT
      value: "{{{decorator-internal-script}}}"
    - name: DECORATOR_INTERNAL_STYLING
      value: "{{{decorator-internal-styling}}}"
  accessPolicy:
    outbound:
      rules:
        - application: tiltak-refusjon-api
      {{#if azure}}
      external:
        - host: login.microsoftonline.com
      {{/if}}
