apiVersion: 'nais.io/v1alpha1'
kind: 'Application'
metadata:
  name: tiltak-refusjon
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - {{{ingress}}}
  liveness:
    path: /tiltak-refusjon/internal/isAlive
    initialDelay: 5
  readiness:
    path: /tiltak-refusjon/internal/isReady
    initialDelay: 5
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: /etc/ssl/ca-bundle.pem
    - name: LOGIN_URL
      value: {{{selvbetjening-login-url}}}
    - name: APIGW_URL
      value: "http://tiltak-refusjon-api"

