packages:
  - arbeidsgiver
  - komponenter
  - saksbehandler

allowBuilds:
  '@sentry/cli': true
  esbuild: true

ignoredBuiltDependencies:
  - '@sentry/cli'
  - esbuild

lockfileIncludeTarballUrl: true