ingress: https://tiltak-refusjon.dev.nav.no
host:
  - www.nav.no
env:
  DECORATOR_URL: https://www.nav.no/dekoratoren
  API_AUDIENCE: "dev-gcp:arbeidsgiver:tiltak-refusjon-api"
slack_alert_channel: arbeidsgiver-notifications-test