apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: tiltak-refusjon-utside
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  {{#if labs}}
  replicas:
    min: 1
    max: 1
  {{/if}}
  ingresses:
    - {{ingress}}
  liveness:
    path: /isAlive
    initialDelay: 10
  readiness:
    path: /isReady
    initialDelay: 10
  env:
    {{#each env}}
    - name: "{{@key}}"
      value: "{{this}}"
    {{/each}}
    - name: HOST
      value: {{ingress}}

  {{#if labs}}
  accessPolicy:
    outbound:
    rules:
      - application: tiltak-refusjon-api
  {{/if}}
  {{#unless labs}}
  replicas:
    min: 1
    max: 2
  tokenx:
    enabled: true
  idporten:
    enabled: true
  accessPolicy:
    outbound:
      rules:
        {{#each outbound}}
          - application: "{{this}}"
        {{/each}}

      external:
      {{#each host}}
        - host: "{{this}}"
      {{/each}}

  envFrom:
    - secret: tiltak-refusjon-session-encrypt-key
    - secret: tiltak-refusjon-utside-redis
  {{/unless}}