ingresses:
    - "https://arbeidsgiver.nav.no/tiltak-refusjon"
login-url: "https://loginservice.nav.no/login?redirect=https://arbeidsgiver.nav.no/tiltak-refusjon"
name: "tiltak-refusjon-utside"
azure: false
decorator-url: "https://www.nav.no/dekoratoren/?context=arbeidsgiver&redirectToApp=true&level=Level4/no/"