ingresses:
    - "https://arbeidsgiver.nav.no/tiltak-refusjon"
    - "https://arbeidsgiver.adeo.no/tiltak-refusjon"
selvbetjening-login-url: "https://loginservice.nav.no/login?redirect=https://arbeidsgiver.nav.no/tiltak-refusjon"

