ingresses:
    - "https://arbeidsgiver.adeo.no/tiltak-refusjon"
login-url: "https://loginservice.nav.no/login?redirect=https://arbeidsgiver.adeo.no/tiltak-refusjon"
name: tiltak-refusjon-innside
azure: true