name: Bygg branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    name: Bygg branch
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Konfigurer Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://npm.pkg.github.com'
      - name: Installer
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Installer - Saksbehandler/Server
        run: npm ci
        working-directory: saksbehandler/server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Installer - Arbeidsgiver/Server
        run: npm ci
        working-directory: arbeidsgiver/server
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Prettier
        run: npm run prettier
      - name: Linting
        run: npm run lint
      - name: Komponenter - bygg
        run: npm run build -w komponenter
      - name: Test og bygg - Saksbehandler
        run: npm run test-and-build -w saksbehandler
      - name: Bygg - Saksbehandler/Server
        run: npm run build
        working-directory: saksbehandler/server
      - name: Test og bygg - Arbeidsgiver
        run: npm run test-and-build -w arbeidsgiver
      - name: Bygg - Arbeidsgiver/Server
        run: npm run build
        working-directory: arbeidsgiver/server
