name: Bygg branch

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  build:
    name: Bygg branch
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Sett opp pnpm
        uses: pnpm/action-setup@v4
      - name: Konfigurer Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'pnpm'
      - name: Konfigurer pnpm
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm config set engine-strict true
      - name: Installer
        run: pnpm install --frozen-lockfile
      - name: Installer - Saksbehandler/Server
        # saksbehandler/server is not part of the pnpm workspace, so we install its
        # dependencies independently with --ignore-workspace
        run: pnpm install --ignore-workspace --frozen-lockfile
        working-directory: saksbehandler/server
      - name: Installer - Arbeidsgiver/Server
        # arbeidsgiver/server is not part of the pnpm workspace, so we install its
        # dependencies independently with --ignore-workspace
        run: pnpm install --ignore-workspace --frozen-lockfile
        working-directory: arbeidsgiver/server
      - name: Prettier
        run: pnpm run prettier
      - name: Linting
        run: pnpm run lint
      - name: Komponenter - bygg
        run: pnpm --filter tiltak-refusjon-komponenter run build
      - name: Test og bygg - Saksbehandler
        run: pnpm --filter tiltak-refusjon-saksbehandler run test-and-build
      - name: Bygg - Saksbehandler/Server
        run: pnpm run build
        working-directory: saksbehandler/server
      - name: Test og bygg - Arbeidsgiver
        run: pnpm --filter tiltak-refusjon-arbeidsgiver run test-and-build
      - name: Bygg - Arbeidsgiver/Server
        run: pnpm run build
        working-directory: arbeidsgiver/server
