name: Bygg master og deploy dev-gcp og labs-gcp

on:
  push:
    branches:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  IMAGE_BASE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}
  IMAGE: docker.pkg.github.com/${{ github.repository }}/${{ github.event.repository.name }}:${{ github.sha }}

jobs:
  bygg:
    name: Bygg og deploy dev-gcp
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2
      - name: Server yarn install
        working-directory: ./server
        run: yarn install
      - name: Server yarn build
        working-directory: ./server
        run: yarn build
      - name: Frontend yarn install
        run: yarn install
      - name: Frontend yarn build
        run: yarn build
      - name: Bygg, tag og push Docker-image
        run: |
          docker build --tag $IMAGE --tag $IMAGE_BASE:latest .
          echo $GITHUB_TOKEN | docker login docker.pkg.github.com -u $GITHUB_REPOSITORY --password-stdin
          docker push $IMAGE_BASE
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: .nais/nais.yml,.nais/redis.yml,.nais/alerts.yml
          VARS: .nais/dev.yml
          PRINT_PAYLOAD: true

  deploy-labs-gcp:
    name: Deploy til labs-gcp
    runs-on: ubuntu-latest
    needs: bygg
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v2

      - name: Deploy til labs-gcp
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: labs-gcp
          RESOURCE: .nais/nais.yml
          PRINT_PAYLOAD: true
          VARS: nais/labs.yml