name: Arbeidsgiver - Bygg og deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'arbeidsgiver/**'
      - 'komponenter/**'
  workflow_dispatch:

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  bygg:
    name: Bygg og deploy
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    env:
      NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Sett opp pnpm
        uses: pnpm/action-setup@v4
      - name: Konfigurer Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml
      - name: Konfigurer pnpm
        run: |
          pnpm config set //npm.pkg.github.com/:_authToken $NODE_AUTH_TOKEN
          pnpm config set engine-strict true
      - name: Installer
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Installer - Server
        run: pnpm install --ignore-workspace --frozen-lockfile --prefer-offline
        working-directory: arbeidsgiver/server
      - name: Prettier
        run: pnpm run prettier
      - name: Linting
        run: pnpm run lint
      - name: Komponenter - bygg
        run: pnpm --filter tiltak-refusjon-komponenter run build
      - name: Test og bygg
        run: pnpm --filter tiltak-refusjon-arbeidsgiver run test-and-build
      - name: Bygg - Server
        run: pnpm run build
        working-directory: arbeidsgiver/server
      - name: Sett opp sentry release
        run: pnpm --filter tiltak-refusjon-arbeidsgiver run release
      - name: Push docker image to GAR
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: arbeidsgiver
          image_suffix: arbeidsgiver
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
          dockerfile: arbeidsgiver/Dockerfile

  deploy-dev:
    name: Deploy til dev-gcp
    runs-on: ubuntu-latest
    needs: bygg
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/arbeidsgiver/nais.yml
          VARS: .nais/arbeidsgiver/dev.yml
          VAR: image=${{ needs.bygg.outputs.image }}

  deploy-labs:
    name: Deploy til dev-gcp (tidligere labs)
    runs-on: ubuntu-latest
    needs: bygg
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/arbeidsgiver/nais.yml
          VARS: .nais/arbeidsgiver/labs.yml
          VAR: image=${{ needs.bygg.outputs.image }}

  deploy-prod:
    name: Deploy til prod-gcp
    runs-on: ubuntu-latest
    needs: [bygg, deploy-dev, deploy-labs]
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Sjekk ut kode
        uses: actions/checkout@v4
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/arbeidsgiver/nais.yml
          VARS: .nais/arbeidsgiver/prod.yml
          VAR: image=${{ needs.bygg.outputs.image }}
